blank_issues_enabled: true
contact_links:
  - name: SingularityNET-Archive Community Support
    url: https://github.com/orgs/SingularityNET-Archive/discussions/categories/q-a
    about: Please ask and answer questions here.
